### PR TITLE
Created BeamParticleIdTool with first pass logic.

### PR DESCRIPTION
**Pull request by StevenGreen1**

### CODE REVIEW

**Comment by PandoraPFA** [comment]
Thanks - do you have the associated ```PandoraSettings_Master_ProtoDUNE.xml``` snippet too?

**Comment by StevenGreen1** [comment]
Hi, 

This is the snippet: 
        <SliceIdTools>
            
            <tool type = "LArBeamParticleId">
                <SelectAllBeamParticles>false</SelectAllBeamParticles>
                <ProjectionIntersectionCut>100.0</ProjectionIntersectionCut>
                <SelectOnlyFirstSliceBeamParticles>false</SelectOnlyFirstSliceBeamParticles>
                <BeamTPCIntersection>-33.051 461.06 0</BeamTPCIntersection>
                <VisualizeID>false</VisualizeID>
            </tool>
        </SliceIdTools>

Cheers

**Comment by PandoraPFA** [comment]
This is where I'm currently at with this: [BeamParticleIdTool.cc](https://github.com/johnmarshall80/LArContent/blob/feature/BeamParticleIDAnalysis/larpandoracontent/LArControlFlow/BeamParticleIdTool.cc), [BeamParticleIdTool.h](https://github.com/johnmarshall80/LArContent/blob/feature/BeamParticleIDAnalysis/larpandoracontent/LArControlFlow/BeamParticleIdTool.h)

**Comment by PandoraPFA** [comment]
Merged in development sprint today!

**Pull request closed without merging**
