### PR TITLE
Max Hits Cut

### PR DESCRIPTION
**Pull request by StevenGreen1**
Adding optional cut on number of hits in event to pre processing algorithm.

### CODE REVIEW

**Comment by StevenGreen1** [comment]
Hi John, 

I've applied the changes you requested to this PR.  I also added a noexcept function to reduce the code in the catch block.  I believe this is good to be merged now if you're happy with it?

Cheers
Steve

**Comment by PandoraPFA** [comment]
Looks good to me - thank you!

**Comment by loressa** [comment]
Hi,

Looks good and clean to me. 

Thanks,
Lorena

**Comment by StevenGreen1** [comment]
This has been merged into the master, but was first rebased to ensure a clean history.
Cheers
Steve

**Pull request closed without merging**
