### PR TITLE
Added the possibility of using... 

### PR DESCRIPTION
**Pull request by loressa**
...SVM probability instead of binary classification

### CODE REVIEW

**Comment by PandoraPFA** [comment]
All looks good, but you should: i) check the indentation, and, ii), set the probability cut to a configurable parameter (even though it's almost always going to remain as 0.5f here, it's always best to avoid having a situation where you can't modify cut values without needing to release new code).

**Comment by loressa** [comment]
Aargh, sorry about the indentation. The configurable parameter for the probability cut was a good idea.

**Comment by PandoraPFA** [comment]
Whitespace change, and floating point operator<=

Will fix up and merge via command line.

**Comment by PandoraPFA** [comment]
Merged. Should there be an associated pull request to MachineLearningData, with an updated SVM file?

**Pull request closed without merging**
